# Generated by Django 2.2.1 on 2019-05-16 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('thumbnail', models.ImageField(blank='True', upload_to='static/')),
                ('description', models.CharField(blank='True', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(blank='True', upload_to='static/')),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photogallery.Archive')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank='True', upload_to='static/')),
                ('caption', models.CharField(max_length=500)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photogallery.Gallery')),
            ],
        ),
    ]
