# Generated by Django 2.2.1 on 2019-05-16 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='archive',
            field=models.ForeignKey(default='buildings', on_delete=django.db.models.deletion.CASCADE, to='photogallery.Archive'),
        ),
    ]
