# Generated by Django 2.2.1 on 2019-05-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0004_auto_20190516_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='displayname',
            field=models.CharField(default=models.CharField(max_length=200, unique=True), max_length=200),
        ),
    ]
